name: elnetpy-dev
dependencies:
  - python=3.7
  - pybind11
  - pandas
  - numpy
  - black
  - isort
  - flake8
  - scipy
  - pytest
  - pytest-benchmark
  - scikit-learn
  - coverage
  - coverage-badge
