name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
          architecture: "x64"
      - name: Install the library
        run: |
          pip install pytest coverage coverage-badge pybind11 glmnet
          pip install -e .
      - name: Run unit tests and print coverage
        run: |
          coverage run -m pytest tests/unit_tests
          coverage report
      - name: Commit coverage badge for master pushes
        if: github.ref == 'refs/heads/master'
        run: |
          coverage-badge -o .github/badges/coverage.svg
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          git add .github/badges/coverage.svg
          git commit --amend --no-edit
          git push -f origin master
